### ISSUE TITLE
dependencies too much

### ISSUE THREAD

**Issue by weiwu-zhang** [bluppfisk/coindicator#74]
With a Ubuntu 20.10 set up that has a lot of desktop software installed, this package still yields the additional:

````
  libblkid-dev libbrotli-dev libcairo-script-interpreter2 libcairo2-dev libffi-dev libfontconfig1-dev libfreetype-dev
  libfreetype6-dev libglib2.0-dev libglib2.0-dev-bin libmikmod3 libmount-dev libpcre16-3 libpcre2-dev libpcre2-posix2 libpcre3-dev
  libpcre32-3 libpcrecpp0v5 libpixman-1-dev libpng-dev libpng-tools libportmidi0 libsdl-image1.2 libsdl-mixer1.2 libsdl-ttf2.0-0
  libselinux1-dev libsepol1-dev libxcb-render0-dev libxcb-shm0-dev libxext-dev libxrender-dev python3-numpy python3-pygame
  uuid-dev x11proto-xext-dev
````

Wonder why so many packages are needed?

**Comment by bluppfisk** [comment]
This is probably true, but I presently don't have the time to figure out which ones are necessary. Those -dev packages can probably go and be replaced by their non -dev versions, but I'm not sure. Would you be keen to play around with it in a virtual machine? :)

**Comment by colourful-land** [comment]
looking at dependencies:

python3-pygame yields

    gfortran python-numpy-doc python3-numpy-dbg python-pygame-doc timidity

libcairo2-dev yields
````
  libblkid-dev libbrotli-dev libcairo-script-interpreter2 libcairo2-dev
  libffi-dev libfontconfig1-dev libfreetype-dev libfreetype6-dev
  libglib2.0-dev libglib2.0-dev-bin libmount-dev libpcre16-3 libpcre2-dev
  libpcre2-posix2 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-dev
  libpng-dev libpng-tools libselinux1-dev libsepol1-dev libxcb-render0-dev
  libxcb-shm0-dev libxext-dev libxrender-dev uuid-dev x11proto-xext-devn
````

libdbus-glib-1-2 yields

````
  accountsservice-ubuntu-schemas indicator-common python3-docopt
  python3-feedparser python3-numpydoc python3-prompt-toolkit
  python3-setproctitle python3-sigmavirus24-urltemplate xonsh
````

gir1.2-gtk-3.0 yields
````
  accountsservice-ubuntu-schemas indicator-common python3-docopt
  python3-feedparser python3-numpydoc python3-prompt-toolkit
  python3-setproctitle python3-sigmavirus24-urltemplate xonsh
````

gir1.2-appindicator3-0.1 yields
````
  accountsservice-ubuntu-schemas indicator-common python3-docopt
  python3-feedparser python3-numpydoc python3-prompt-toolkit
  python3-setproctitle python3-sigmavirus24-urltemplate xonsh
````

Look like libcairo2-dev is the one that has most dependencies. But I'm not seeing it used in the source (is it?)

**Comment by colourful-land** [comment]
Regarding gir, I failed to see what it does. There seems to be no use of gir in the source code either, unless `grep` isn't the way to look for.

**Comment by bluppfisk** [comment]
gir seems necessary for the appindicator interface which allows you to create the top menu bar icons and menus. I think libcairo2-dev can be dropped from the requirements. I need time to test this all out :)

If it works for you, kindly let me know which distro :)

**Comment by bluppfisk** [comment]
Strongly reduced dependencies in 2.0.1
