### ISSUE TITLE
I Cant Install

### ISSUE THREAD

**Issue by Umair8t** [bluppfisk/coindicator#93]
Hello,
After i ran the install.sh i got the error.

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcairo2-dev is already the newest version (1.16.0-5).
libdbus-glib-1-2 is already the newest version (0.110-6).
gir1.2-gtk-3.0 is already the newest version (3.24.24-4+deb11u2).
python3-pip is already the newest version (20.3.4-4+deb11u1).
python3-venv is already the newest version (3.9.2-3).
gir1.2-appindicator3-0.1 is already the newest version (0.4.92-7).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Requirement already satisfied: pygame in /usr/local/lib/python3.9/dist-packages (2.1.2)
Requirement already satisfied: certifi==2018.8.24 in ./lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2018.8.24)
Requirement already satisfied: chardet==3.0.4 in ./lib/python3.9/site-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna==2.7 in ./lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2.7)
Requirement already satisfied: notify2==0.3.1 in ./lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.3.1)
Requirement already satisfied: PyYAML>=4.2b1 in ./lib/python3.9/site-packages (from -r requirements.txt (line 5)) (6.0)
Requirement already satisfied: requests~=2.20 in ./lib/python3.9/site-packages (from -r requirements.txt (line 6)) (2.28.1)
Requirement already satisfied: urllib3~=1.26.5 in ./lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.26.11)
Requirement already satisfied: websockets==9.1 in ./lib/python3.9/site-packages (from -r requirements.txt (line 8)) (9.1)
Requirement already satisfied: charset-normalizer<3,>=2 in ./lib/python3.9/site-packages (from requests~=2.20->-r requirements.txt (line 6)) (2.1.0)
/root/.local/share/applications/coindicator.desktop: error: file contains multiple keys named "Exec" in group "Desktop Entry"
/root/.local/share/applications/coindicator.desktop: error: file contains multiple keys named "Icon" in group "Desktop Entry"
Error on file "coindicator.desktop": Failed to validate the created desktop file
root@debian01:/home/umair/Downloads/coinprice-indicator-master# 

Best Regards

**Comment by bluppfisk** [comment]
looks like the coindicator.desktop was corrupted You can remove the one in share/applications and reinstall the one from this repo

**Comment by bluppfisk** [comment]
I've updated the install script, things should work better now.

**Comment by Umair8t** [comment]
Still I cant install.... :((

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libdbus-glib-1-2 is already the newest version (0.112-2build1).
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+20.10.20200706.1-0ubuntu1).
patchelf is already the newest version (0.14.3-1).
python3-pip is already the newest version (22.0.2+dfsg-1).
gir1.2-gtk-3.0 is already the newest version (3.24.33-1ubuntu2).
python3-gi is already the newest version (3.42.1-0ubuntu1).
python3-gi-cairo is already the newest version (3.42.1-0ubuntu1).
python3-venv is already the newest version (3.10.6-1~22.04).
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-43 linux-headers-5.15.0-43-generic
  linux-image-5.15.0-43-generic linux-modules-5.15.0-43-generic
  linux-modules-extra-5.15.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Collecting coindicator
  Using cached coindicator-2.0.3.tar.gz (474 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/2d/5b/f1a29246312dd177ee66999f0480ea3a02da1e5d3c86d0a0d4beba376503/coindicator-2.0.3.tar.gz#sha256=b9194482a142c35931c6e5533715406491938c6e4bd49d065eefd40feab0476c (from https://pypi.org/simple/coindicator/): Requested coindicator from https://files.pythonhosted.org/packages/2d/5b/f1a29246312dd177ee66999f0480ea3a02da1e5d3c86d0a0d4beba376503/coindicator-2.0.3.tar.gz#sha256=b9194482a142c35931c6e5533715406491938c6e4bd49d065eefd40feab0476c has inconsistent version: filename has '2.0.3', but metadata has '0.0.0'
  Using cached coindicator-2.0.2.tar.gz (474 kB)
  Preparing metadata (setup.py) ... done
Collecting PyGObject~=3.42.2
  Using cached PyGObject-3.42.2.tar.gz (719 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: PyYAML>=4.2b1 in /usr/lib/python3/dist-packages (from coindicator) (5.4.1)
Collecting certifi~=2018.8.24
  Using cached certifi-2018.8.24-py2.py3-none-any.whl (147 kB)
Collecting chardet~=3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting dbus-python~=1.3.2
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      + meson setup --native-file=/tmp/pip-install-n0qmjtv3/dbus-python_721b576f45414c208d03c0603913e1b5/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/usr /tmp/pip-install-n0qmjtv3/dbus-python_721b576f45414c208d03c0603913e1b5 /tmp/pip-install-n0qmjtv3/dbus-python_721b576f45414c208d03c0603913e1b5/.mesonpy-70ncjc0f/build
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "/tmp/pip-build-env-bp9hzzoe/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/usr/lib/python3.10/subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'meson'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pi

**Comment by bluppfisk** [comment]
does apt install meson solve it?

**Comment by Umair8t** [comment]
No....

umair@myubuntu:~/Downloads/coindicator-master$ sudo apt install meson 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
meson is already the newest version (0.61.2-1).
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-43 linux-headers-5.15.0-43-generic linux-image-5.15.0-43-generic linux-modules-5.15.0-43-generic
  linux-modules-extra-5.15.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
umair@myubuntu:~/Downloads/coindicator-master$ sh install.sh 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libdbus-glib-1-2 is already the newest version (0.112-2build1).
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+20.10.20200706.1-0ubuntu1).
patchelf is already the newest version (0.14.3-1).
python3-pip is already the newest version (22.0.2+dfsg-1).
gir1.2-gtk-3.0 is already the newest version (3.24.33-1ubuntu2).
python3-gi is already the newest version (3.42.1-0ubuntu1).
python3-gi-cairo is already the newest version (3.42.1-0ubuntu1).
python3-venv is already the newest version (3.10.6-1~22.04).
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-43 linux-headers-5.15.0-43-generic linux-image-5.15.0-43-generic linux-modules-5.15.0-43-generic
  linux-modules-extra-5.15.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Collecting coindicator
  Using cached coindicator-2.0.3.tar.gz (474 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/2d/5b/f1a29246312dd177ee66999f0480ea3a02da1e5d3c86d0a0d4beba376503/coindicator-2.0.3.tar.gz#sha256=b9194482a142c35931c6e5533715406491938c6e4bd49d065eefd40feab0476c (from https://pypi.org/simple/coindicator/): Requested coindicator from https://files.pythonhosted.org/packages/2d/5b/f1a29246312dd177ee66999f0480ea3a02da1e5d3c86d0a0d4beba376503/coindicator-2.0.3.tar.gz#sha256=b9194482a142c35931c6e5533715406491938c6e4bd49d065eefd40feab0476c has inconsistent version: filename has '2.0.3', but metadata has '0.0.0'
  Using cached coindicator-2.0.2.tar.gz (474 kB)
  Preparing metadata (setup.py) ... done
Collecting PyGObject~=3.42.2
  Using cached PyGObject-3.42.2.tar.gz (719 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: PyYAML>=4.2b1 in /usr/lib/python3/dist-packages (from coindicator) (5.4.1)
Collecting certifi~=2018.8.24
  Using cached certifi-2018.8.24-py2.py3-none-any.whl (147 kB)
Collecting chardet~=3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting dbus-python~=1.3.2
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      The Meson build system
      Version: 0.61.2
      Source dir: /tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be
      Build dir: /tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be/.mesonpy-gbkh5t7_/build
      Build type: native build
      Project name: dbus-python
      Project version: 1.3.2
      C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
      C linker for the host machine: cc ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -fno-common: YES
      Compiler for C supports arguments -Wno-missing-field-initializers: YES
      Compiler for C supports arguments -Wno-declaration-after-statement: YES
      Compiler for C supports arguments -Wno-inline: YES
      Compiler for C supports arguments -Wno-redundant-decls: YES
      Compiler for C supports arguments -Wno-switch-default: YES
      Compiler for C supports arguments -Wno-write-strings: YES
      Compiler for C supports arguments -Wcast-align: YES
      Compiler for C supports arguments -Wdouble-promotion: YES
      Compiler for C supports arguments -Wduplicated-cond: YES
      Compiler for C supports arguments -Wfloat-equal: YES
      Compiler for C supports arguments -Wformat-nonliteral: YES
      Compiler for C supports arguments -Wformat-security: YES
      Compiler for C supports arguments -Wformat=2: YES
      Compiler for C supports arguments -Winit-self: YES
      Compiler for C supports arguments -Wlogical-op: YES
      Compiler for C supports arguments -Wmissing-declarations: YES
      Compiler for C supports arguments -Wmissing-format-attribute: YES
      Compiler for C supports arguments -Wmissing-include-dirs: YES
      Compiler for C supports arguments -Wmissing-noreturn: YES
      Compiler for C supports arguments -Wnull-dereference: YES
      Compiler for C supports arguments -Wpacked: YES
      Compiler for C supports arguments -Wpointer-arith: YES
      Compiler for C supports arguments -Wshadow: YES
      Compiler for C supports arguments -Wswitch-enum: YES
      Compiler for C supports arguments -Wundef: YES
      Compiler for C supports arguments -Wunused-but-set-variable: YES
      Compiler for C supports arguments -Wjump-misses-init: YES
      Compiler for C supports arguments -Wmissing-prototypes: YES
      Compiler for C supports arguments -Wnested-externs: YES
      Compiler for C supports arguments -Wold-style-definition: YES
      Compiler for C supports arguments -Wpointer-sign: YES
      Compiler for C supports arguments -Wstrict-prototypes: YES
      Configuring _dbus-python-config.h using configuration
      
      Executing subproject dbus-gmain
      
      dbus-gmain| Project name: dbus-gmain
      dbus-gmain| Project version: undefined
      dbus-gmain| C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
      dbus-gmain| C linker for the host machine: cc ld.bfd 2.38
      dbus-gmain| Compiler for C supports arguments -fno-common: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wcast-align: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wdouble-promotion: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wduplicated-branches: YES
      dbus-gmain| Compiler for C supports arguments -Wduplicated-cond: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wfloat-equal: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-nonliteral: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-security: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat=2: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Winit-self: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wlogical-op: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-declarations: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-format-attribute: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-include-dirs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-noreturn: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnull-dereference: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpacked: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-arith: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wredundant-decls: YES
      dbus-gmain| Compiler for C supports arguments -Wshadow: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wswitch-default: YES
      dbus-gmain| Compiler for C supports arguments -Wswitch-enum: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wundef: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wunused-but-set-variable: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wwrite-strings: YES
      dbus-gmain| Compiler for C supports arguments -Wdeclaration-after-statement: YES
      dbus-gmain| Compiler for C supports arguments -Wjump-misses-init: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-prototypes: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnested-externs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wold-style-definition: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-sign: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wstrict-prototypes: YES (cached)
      dbus-gmain| Found pkg-config: /usr/bin/pkg-config (0.29.2)
      dbus-gmain| Did not find CMake 'cmake'
      dbus-gmain| Found CMake: NO
      dbus-gmain| Run-time dependency dbus-1 found: NO (tried pkgconfig)
      
      ../../subprojects/dbus-gmain/meson.build:107:0: ERROR: Dependency "dbus-1" not found, tried pkgconfig
      
      A full log can be found at /tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be/.mesonpy-gbkh5t7_/build/meson-logs/meson-log.txt
      + meson setup --native-file=/tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/usr /tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be /tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be/.mesonpy-gbkh5t7_/build
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "/tmp/pip-build-env-c67peiug/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/usr', '/tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be', '/tmp/pip-install-_en22e63/dbus-python_519b42adfb56434ebed57c52646241be/.mesonpy-gbkh5t7_/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
umair@myubuntu:~/Downloads/coindicator-master$

**Comment by bluppfisk** [comment]
yes to build dbus you'd need a bunch of dependencies
do you have `python3-wheel` installed? I'd assume it could pull a wheel instead of building dbus from source.

**Comment by Umair8t** [comment]
yes it is installed:

umair@myubuntu:~/Desktop$ sudo apt-get install -y python3-wheel
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-wheel is already the newest version (0.37.1-2).
python3-wheel set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-43 linux-headers-5.15.0-43-generic linux-image-5.15.0-43-generic linux-modules-5.15.0-43-generic
  linux-modules-extra-5.15.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
umair@myubuntu:~/Desktop$

**Comment by bluppfisk** [comment]
there's a few cues here, may depend on which distro you are using:

https://stackoverflow.com/questions/61285415/no-package-dbus-1-found

**Comment by Umair8t** [comment]
Installation is done i think after many tries umair@myubuntu:~/Downloads/coindicator-master$ sh install.sh 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libdbus-glib-1-2 is already the newest version (0.112-2build1).
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+20.10.20200706.1-0ubuntu1).
patchelf is already the newest version (0.14.3-1).
python3-pip is already the newest version (22.0.2+dfsg-1).
gir1.2-gtk-3.0 is already the newest version (3.24.33-1ubuntu2).
python3-gi is already the newest version (3.42.1-0ubuntu1).
python3-gi-cairo is already the newest version (3.42.1-0ubuntu1).
python3-venv is already the newest version (3.10.6-1~22.04).
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-43 linux-headers-5.15.0-43-generic linux-image-5.15.0-43-generic linux-modules-5.15.0-43-generic
  linux-modules-extra-5.15.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: coindicator in /home/umair/.local/lib/python3.10/site-packages (2.0.2)
Collecting coindicator
  Using cached coindicator-2.0.3.tar.gz (474 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/2d/5b/f1a29246312dd177ee66999f0480ea3a02da1e5d3c86d0a0d4beba376503/coindicator-2.0.3.tar.gz#sha256=b9194482a142c35931c6e5533715406491938c6e4bd49d065eefd40feab0476c (from https://pypi.org/simple/coindicator/): Requested coindicator from https://files.pythonhosted.org/packages/2d/5b/f1a29246312dd177ee66999f0480ea3a02da1e5d3c86d0a0d4beba376503/coindicator-2.0.3.tar.gz#sha256=b9194482a142c35931c6e5533715406491938c6e4bd49d065eefd40feab0476c has inconsistent version: filename has '2.0.3', but metadata has '0.0.0'
Requirement already satisfied: pycairo~=1.21.0 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (1.21.0)
Requirement already satisfied: pygame~=2.1.2 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (2.1.2)
Requirement already satisfied: urllib3~=1.26.5 in /usr/lib/python3/dist-packages (from coindicator) (1.26.5)
Requirement already satisfied: certifi~=2018.8.24 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (2018.8.24)
Requirement already satisfied: chardet~=3.0.4 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (3.0.4)
Requirement already satisfied: notify2~=0.3.1 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (0.3.1)
Requirement already satisfied: dbus-python~=1.3.2 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (1.3.2)
Requirement already satisfied: idna~=2.7 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (2.10)
Requirement already satisfied: PyYAML>=4.2b1 in /usr/lib/python3/dist-packages (from coindicator) (5.4.1)
Requirement already satisfied: PyGObject~=3.42.2 in /home/umair/.local/lib/python3.10/site-packages (from coindicator) (3.42.2)
Requirement already satisfied: requests~=2.20 in /usr/lib/python3/dist-packages (from coindicator) (2.25.1)


Now how to run?

**Comment by Umair8t** [comment]
umair@myubuntu:~/Downloads/coindicator-master$ python3 src/coin/coin.py &
[1] 4140
umair@myubuntu:~/Downloads/coindicator-master$ Traceback (most recent call last):
  File "/home/umair/Downloads/coindicator-master/src/coin/coin.py", line 29, in <module>
    from coin.about import AboutWindow
  File "/home/umair/Downloads/coindicator-master/src/coin/coin.py", line 29, in <module>
    from coin.about import AboutWindow
ModuleNotFoundError: No module named 'coin.about'; 'coin' is not a package

**Comment by bluppfisk** [comment]
after running ./install.sh it should be available from the applications menu on Ubuntu. Alternatively, you can simply run 'coin'.

**Comment by Umair8t** [comment]
from application there is no response from command it shows:

umair@myubuntu:/Downloads/coindicator-master$ python3 src/coin/coin.py &
[1] 4140
umair@myubuntu:/Downloads/coindicator-master$ Traceback (most recent call last):
File "/home/umair/Downloads/coindicator-master/src/coin/coin.py", line 29, in
from coin.about import AboutWindow
File "/home/umair/Downloads/coindicator-master/src/coin/coin.py", line 29, in
from coin.about import AboutWindow
ModuleNotFoundError: No module named 'coin.about'; 'coin' is not a package

**Comment by bluppfisk** [comment]
should be installed as an executable, no need to use python3

**Comment by Umair8t** [comment]
yes, i can see but it is not working. for your kind information i am running your app on VMWare Workstation VM is there anything else i need to do?

**Comment by bluppfisk** [comment]
have you tried running just `coin` from the shell?
